version: '3.9'
services:
  spring-app:
    build: .
    container_name: spring-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.1:3307/externaldb_wsl
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    restart: unless-stopped
